# Dockerfile.birdnet_image_demo_mac
FROM python:3.9-slim

RUN apt-get update && apt-get install -y python3-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY modules/ .
COPY config/ config/

RUN pip install --no-cache-dir requests numpy pyyaml

CMD ["python", "mac-M/birdnet_image_demo_mac.py"]
