# Dockerfile.birdnet_image_demo_mac
# For Mac (M series)
FROM python:3.9-slim

RUN apt-get update && apt-get install -y python3-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the modules and config folders into the container
COPY modules/ ./modules/
COPY config/ ./config/

# Install required Python dependencies
RUN pip install --no-cache-dir requests numpy pyyaml

# Run the mac version of the birdnet image demo module
CMD ["python", "modules/mac-M/birdnet_image_demo_mac.py"]
