version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Docker command execution
      - ./log:/app/log                              # Mount the log folder for command logs and current-docker-compose.yml
    # 'privileged: true' is included for Linux systems; on Mac/Windows it may be ignored.
    privileged: true
    restart: always
