version: "3.8"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Grant Docker command access
      - ./log:/app/log                              # Mount log folder to capture command logs
    privileged: true
    restart: always
