# Dockerfile.birdnet_analyzer
FROM arm64v8/python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the modules folder into the container
COPY modules/ .
COPY config/ config/

# Install required Python libraries
RUN pip install --no-cache-dir numpy birdnetlib requests

# Run the BirdNET analyzer module
CMD ["python", "birdnet_analyzer.py"]
