# Global configuration parameters for the Digital Ecology Sensing Network.
global:
  MACHINE_ID:  personal_mac   # ID name of the machine in use
  MACHINE_TYPE: mac-M         # Type of machine in use (pi, mac-M, etc.)

# Module selection, definitions, associated file names, and parameters.
modules:
  #--------------------------------------------------------------------------------------------------------------
  audio_recording:
    system_type: pi           # System type for which module was built
    available: true           # Audio recording module is working.
    using: false              # Audio recording module is used on current machine.
    main_code_fname: modules/pi/audio_recording/audio_recording.py  # Main code file for the audio recording module.
    dockerfile_fname: modules/pi/audio_recording/Dockerfile.audio_recording  # Dockerfile for the audio recording module.
    parameters:
      DATA_FOLDER: local_data/audio_recordings_DATA/           # Folder to Store Output Recordings in ./local_data
      BUFFER_SIZE: 2                        # Number of audio chunks to combine per recording (e.g., 2 chunks)
      CHUNK_DURATION: 6                     # Duration (in seconds) of each audio chunk recorded
      SAMPLE_RATE: 44100                    # Audio sampling rate in Hz
      CHANNELS: 4                           # Number of audio channels (e.g., microphone configuration)

  #--------------------------------------------------------------------------------------------------------------
  birdnet_analyzer:
    system_type: pi           # System type for which module was built
    available: true           # BirdNET analyzer module is working.
    using: false              # BirdNET analyzer module is used on current machine.
    main_code_fname: modules/pi/birdnet_analyzer/birdnet_analyzer.py  # Main code file for the BirdNET analyzer module.
    dockerfile_fname: modules/pi/birdnet_analyzer/Dockerfile.birdnet_analyzer  # Dockerfile for the BirdNET analyzer module.
    parameters:
        DATA_FOLDER: local_data/birdnet_analysis/           # Folder to Store Output Data in ./local_data
        LEDGER_FILE: local_data/birdnet_analysis/ledger.csv           # Filename of ledger file to store BIRDNET Results
        RECORDINGS_FOLDER: local_data/audio_recordings_DATA/CHANNEL_1/           # Folder to use for audio recordings for birdnet analysis
        MAX_RECORDINGS: 5           # Maximum number of recordings to keep (for cleanup purposes)
        USE_DATE: false             # Use Date when performing birdnet analysis
        USE_LOCATION: false         # Use location when performing birdnet analysis
        LAT: 30.2672                # Latitude for BirdNET analysis (Austin, Texas)
        LON: -97.7431               # Longitude for BirdNET analysis (Austin, Texas)
  #--------------------------------------------------------------------------------------------------------------
  birdnet_image_demo:
    system_type: pi           # System type for which module was built
    available: true           # BirdNET image demo module is working.
    using: false              # BirdNET image demo module is used on current machine.
    main_code_fname: modules/pi/birdnet_image_demo/birdnet_image_demo.py  # Main code file for the BirdNET image demo module.
    dockerfile_fname: modules/pi/birdnet_image_demo/Dockerfile.birdnet_image_demo  # Dockerfile for the BirdNET image demo module.
    parameters:
      DATA_FOLDER: local_data/birdnet_image_demo_DATA/           # Folder to Store Output Data in ./local_data
      LEDGER_FILE: local_data/birdnet_analysis/ledger.csv           # Filename of input ledger file to use for image demo
      CURRENT_BIRD_IMAGE: local_data/birdnet_image_demo_DATA/current_bird.png           # Filename of output png image in image demo

  #--------------------------------------------------------------------------------------------------------------
  audio_recording_mac:
    system_type: mac-M        # System type for which module was built
    available: true           # Mac version of the audio recording working.
    using: true               # Mac version of the audio recording module is used on current machine.
    main_code_fname: modules/mac-M/audio_recording_mac/audio_recording_mac.py  # Main code file for the Mac audio recording module.
    dockerfile_fname: modules/mac-M/audio_recording_mac/Dockerfile.audio_recording_mac  # Dockerfile for the Mac audio recording module.
    parameters:
      DATA_FOLDER: local_data/audio_recordings_DATA/           # Folder to Store Output Recordings in ./local_data
      BUFFER_SIZE: 2                        # Number of audio chunks to combine per recording (e.g., 2 chunks)
      CHUNK_DURATION: 6                     # Duration (in seconds) of each audio chunk recorded
      SAMPLE_RATE: 48000                    # Audio sampling rate in Hz
      CHANNELS: 1                           # Number of audio channels (e.g., microphone configuration)

  #--------------------------------------------------------------------------------------------------------------
  birdnet_analyzer_mac:
    system_type: mac-M        # System type for which module was built
    available: true           # Mac version of the BirdNET analyzer working.
    using: true               # Mac version of the BirdNET analyzer module is used on current machine.
    main_code_fname: modules/mac-M/birdnet_analyzer_mac/birdnet_analyzer_mac.py  # Main code file for the Mac BirdNET analyzer module.
    dockerfile_fname: modules/mac-M/birdnet_analyzer_mac/Dockerfile.birdnet_analyzer_mac  # Dockerfile for the Mac BirdNET analyzer module.
    parameters:
        DATA_FOLDER: local_data/birdnet_analysis/           # Folder to Store Output Data in ./local_data
        LEDGER_FILE: local_data/birdnet_analysis/ledger.csv           # Filename of ledger file to store BIRDNET Results
        RECORDINGS_FOLDER: local_data/audio_recordings_DATA/CHANNEL_1/           # Folder to use for audio recordings for birdnet analysis
        MAX_RECORDINGS: 5           # Maximum number of recordings to keep (for cleanup purposes)
        USE_DATE: false             # Use Date when performing birdnet analysis
        USE_LOCATION: false         # Use location when performing birdnet analysis
        LAT: 30.2672                # Latitude for BirdNET analysis (Austin, Texas)
        LON: -97.7431               # Longitude for BirdNET analysis (Austin, Texas)
  #--------------------------------------------------------------------------------------------------------------
  birdnet_image_demo_mac:
    system_type: mac-M        # System type for which module was built
    available: true           # Mac version of the BirdNET image demo working.
    using: true               # Mac version of the BirdNET image demo module is used on current machine.
    main_code_fname: modules/mac-M/birdnet_image_demo_mac/birdnet_image_demo_mac.py  # Main code file for the Mac BirdNET image demo module.
    dockerfile_fname: modules/mac-M/birdnet_image_demo_mac/Dockerfile.birdnet_image_demo_mac  # Dockerfile for the Mac BirdNET image demo module.
    parameters:
      DATA_FOLDER: local_data/birdnet_image_demo_DATA/           # Folder to Store Output Data in ./local_data
      LEDGER_FILE: local_data/birdnet_analysis/ledger.csv           # Filename of input ledger file to use for image demo
      CURRENT_BIRD_IMAGE: local_data/birdnet_image_demo_DATA/current_bird.png           # Filename of output png image in image demo
